name: Remote Dispatch Action Initiator

on:
  push:

jobs:
  ping-pong:
    runs-on: ubuntu-latest
    steps:
      - name: PING - Dispatch initiating repository 
        if: github.event.action != 'pong'
        run: |
          curl -X POST https://api.github.com/repos/notyan/git-learn/dispatches \
          -H 'Accept: application/vnd.github.everest-preview+json' \
          -u ${{ secrets.ACCESS_TOKEN }} \
          --data '{"event_type": "deploy", "client_payload": { ["repository": "'"$GITHUB_REPOSITORY"'"], [ "commit" : "'"${ GITHUB_SHA::8 }}"'" ] }}'

